### ISSUE TITLE
DynamoDb Locking not used

### ISSUE THREAD

**Issue by CumpsD** [FormidableLabs/aws-lambda-serverless-reference#65]
No clear idea how to deal with this.

You guys create a DynamoDB table: https://github.com/FormidableLabs/aws-lambda-serverless-reference/blob/master/aws/bootstrap.yml#L46

But then here you are not using it: https://github.com/FormidableLabs/aws-lambda-serverless-reference/blob/master/terraform/main.tf#L6

I tried adding `dynamodb_table = "cf-${var.service_name}-${var.stage}-terraform-locks"` but interpolation is not allowed in a backend, so to make it work I would need to manually hardcode change it each time.

Any ideas?

**Comment by ryan-roemer** [comment]
The locks table (and the s3 storage) is only used for TF remote state management and is _not_ part of the TF infrastructure itself.

See: https://github.com/FormidableLabs/aws-lambda-serverless-reference/blob/81ba7a9166df2195246df8794d179202ba37a750/package.json#L39

... we have to do that in CloudFormation because it's a chicken-vs-egg thing with Terraform (it can't start up without state so that has to exist outside of TF)

**Comment by CumpsD** [comment]
@ryan-roemer Thanks for the quick reply :) I didn't spot that in the scripts, my bad!

It is definitely a nicer solution using the CF stack, I used to throw away the TF state, but then you were stuck if you ever wanted to remove it ( https://github.com/Informatievlaanderen/aws-infrastructure#create-a-terraform-remote-state-bucket-and-bootstrap-your-account )
